TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DB += devSRS_PS310_pos.db
DB += devSRS_PS325_pos.db
DB += devSRS_PS350_pos.db
DB += devSRS_PS310_neg.db
DB += devSRS_PS325_neg.db
DB += devSRS_PS350_neg.db
DB += devSRS_PS355.db
DB += devSRS_PS365.db
DB += devSRS_PS370.db
DB += devSRS_PS375.db
DB += devSRS_PS300_common.db
DATA += ps300.proto

#=======================================
include $(TOP)/configure/RULES
